[package]
name = "guest-return"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", default-features = false, features = ["std"] }
colibri = { version = "0.1", default-features = false }
gethostname = "0.5.0"
glib = { version = "0.19", default-features = false, features = ["log"] }
gstreamer = { version = "0.22", default-features = false }
http = { version = "1.1.0", default-features = false }
lib-gst-meet = { version = "0.8", path = "../lib-gst-meet", default-features = false, features = ["tracing-subscriber"] }
regex = "1.10.6"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
rtcp = "0.13.0"
serde = "1.0.204"
serde_json = "1.0.120"
serde_urlencoded = { version = "0.7.1", default-features = false }
structopt = "0.3.26"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal", "sync", "time"], default-features = false }
tokio-stream = "0.1.15"
tracing = { version = "0.1.40", features = ["attributes", "std"] }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.25.0"

[features]
default = ["tls-rustls-native-roots"]
log-rtp = ["lib-gst-meet/log-rtp"]
tls-insecure = ["lib-gst-meet/tls-insecure"]
tls-native = ["lib-gst-meet/tls-native"]
tls-native-vendored = ["lib-gst-meet/tls-native-vendored"]
tls-rustls-native-roots = ["lib-gst-meet/tls-rustls-native-roots"]
tls-rustls-webpki-roots = ["lib-gst-meet/tls-rustls-webpki-roots"]
